apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: certsuite-operator
  namespace: certsuite-operator
spec:
  sourceNamespace: certsuite-operator
  channel: alpha
  name: rh-best-practices-for-k8s-certsuite-operator
  source: certsuite-operator-olm-catalog
