---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-best-practices-for-k8s-openshift-io-v1alpha1-certsuiteconsoleplugin
  failurePolicy: Fail
  name: vcertsuiteconsoleplugin.kb.io
  rules:
  - apiGroups:
    - best-practices-for-k8s.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certsuiteconsoleplugins
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-best-practices-for-k8s-openshift-io-v1alpha1-certsuiterun
  failurePolicy: Fail
  name: vcertsuiterun.kb.io
  rules:
  - apiGroups:
    - best-practices-for-k8s.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certsuiteruns
  sideEffects: None
