apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cnf-certsuite-operator
    app.kubernetes.io/part-of: cnf-certsuite-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - configmaps
  verbs:
  - create
  - get
- apiGroups:
  - "*"
  resources: 
  - "consoles"
  - "pods"
  - "pods/log"
  verbs: 
  - "get"
  - "list"
  - "patch"
  - "update"
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
- apiGroups: 
  - apps
  resources:
  - deployments
  verbs:
  - create
