# permissions for end users to edit certsuiteconsoleplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certsuiteconsoleplugin-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certsuite-operator
    app.kubernetes.io/part-of: certsuite-operator
    app.kubernetes.io/managed-by: kustomize
  name: certsuiteconsoleplugin-editor-role
rules:
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteconsoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteconsoleplugins/status
  verbs:
  - get
