---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteconsoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteconsoleplugins/finalizers
  verbs:
  - update
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteconsoleplugins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: certsuite-operator
rules:
- apiGroups:
  - ""
  resources:
  - configMaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteruns/finalizers
  verbs:
  - update
- apiGroups:
  - best-practices-for-k8s.openshift.io
  resources:
  - certsuiteruns/status
  verbs:
  - get
  - patch
  - update
