---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: console-plugin-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: cnf-certsuite-operator
    app.kubernetes.io/part-of: cnf-certsuite-operator
    app.kubernetes.io/managed-by: kustomize
  name: console-plugin-cert
  namespace: cnf-certsuite-operator
spec:
  dnsNames:
  - cnf-certsuite-plugin.cnf-certsuite-operator.svc
  - cnf-certsuite-plugin.cnf-certsuite-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cnf-certsuite-selfsigned-issuer
  secretName: console-serving-cert
