apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    console.openshift.io/plugins: '["cnf-certsuite-plugin"]'
  name: cnf-certsuite-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CnfCertificationSuiteRun is the Schema for the cnfcertificationsuiteruns
        API
      displayName: Cnf Certification Suite Run
      kind: CnfCertificationSuiteRun
      name: cnfcertificationsuiteruns.cnf-certifications.redhat.com
      version: v1alpha1
  description: Deploys the CNF Certification Suite Pod to run the certification suite
    on target CNF resources.
  displayName: CNF Certification Suite Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cnf
  - certification
  - cloud
  - telco
  links:
  - name: CNF Certification Suite Operator
    url: https://github.com/test-network-function/cnf-certsuite-operator
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
