apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    console.openshift.io/plugins: '["certsuite-plugin"]'
  name: rh-best-practices-for-k8s-certsuite-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CertsuiteConsolePlugin is the Schema for the certsuiteconsoleplugins
        API
      displayName: Certsuite Console Plugin
      kind: CertsuiteConsolePlugin
      name: certsuiteconsoleplugins.best-practices-for-k8s.openshift.io
      version: v1alpha1
    - description: CertsuiteRun is the Schema for the certsuiteruns API
      displayName: Certsuite Run
      kind: CertsuiteRun
      name: certsuiteruns.best-practices-for-k8s.openshift.io
      version: v1alpha1
  description: Deploys Red Hat's Best Practices for Kubernetes Certification Suite
    Pod to run the Certification Test Suite on target resources.
  displayName: Red Hat's Best Practices for Kubernetes Certification Suite Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cnf
  - certification
  - cloud
  - telco
  links:
  - name: Red Hat's Best Practices for Kubernetes Certification Suite Operator
    url: https://github.com/redhat-best-practices-for-k8s/certsuite-operator
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
