# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certsuiteconsoleplugins.best-practices-for-k8s.openshift.io
spec:
  conversion:
    strategy: None
