## Append samples of your project ##

## Uncomment this two files (configmap+secret) to create a runnable test CR in the test namespace.
## Then run them with: oc kustomize config/samples | oc apply -f -
#- extra/certsuite-configmap.yaml
#- extra/certsuite-preflight-secret.yaml

resources:
- best-practices-for-k8s_v1alpha1_certsuiterun.yaml
- extra/certsuite-configmap.yaml
- extra/certsuite-preflight-secret.yaml
- best-practices-for-k8s_v1alpha1_certsuiteconsoleplugin.yaml
#+kubebuilder:scaffold:manifestskustomizesamples

namespace: certsuite-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
