name: Test CnfCertificationSuiteRun webhooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validation:
    name: Test CnfCertificationSuiteRun's validation
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}

      - name: Removed unused docker images and go cache cleanup
        run: |
          df -h
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker builder prune --all -f
          go clean -modcache
          df -h

      - name: Setup the k8s cluster
        uses: palmsoftware/quick-k8s@v0.0.37
        with:
          disableDefaultCni: true
          numControlPlaneNodes: 1
          numWorkerNodes: 3
          installOLM: true
          removeDefaultStorageClass: true
          removeControlPlaneTaint: true

      - name: Build operator
        run: ./scripts/ci/build.sh

      - name: Install cert-manager to cluster
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl wait --for=condition=ready pod --all=true -n cert-manager --timeout=5m

      - name: Install consoleplugin CRD to cluster
        run: |
          kubectl apply -f https://raw.githubusercontent.com/openshift/api/master/console/v1/zz_generated.crd-manifests/90_consoleplugins-Default.crd.yaml

      - name: More cleanup
        run: |
          df -h
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker builder prune --all -f
          go clean -modcache
          rm -rf ${GITHUB_WORKSPACE}/certsuite-sample-workload
          df -h

      - name: Install operator in the Kind cluster
        run: ./scripts/ci/deploy.sh

      - name: Test CnfCertificationSuiteRun's validation
        run: ./scripts/ci/certsuiterun_validation_test.sh
